### ISSUE TITLE
managesites_reset_bulk_actions_params is not defined

### ISSUE THREAD

**Issue by joeczucha** [mainwp/mainwp#694] opened 2024-06-19 10:38 UTC
**Describe the bug**
Since the 5.1 update, clicking "Sites" in the sidebar gives me the error:

    Uncaught ReferenceError: managesites_reset_bulk_actions_params is not defined
        dataSrc https://wordpress.xx.ie/wordpress/wp-admin/admin.php?page=managesites:2791
        get https://wordpress.xx.ie/content/plugins/mainwp/assets/js/datatables/dataTables.js:1656
        _fnAjaxDataSrc https://wordpress.xx.ie/content/plugins/mainwp/assets/js/datatables/dataTables.js:4255
        _fnAjaxUpdateDraw https://wordpress.xx.ie/content/plugins/mainwp/assets/js/datatables/dataTables.js:4189
        _fnAjaxUpdate https://wordpress.xx.ie/content/plugins/mainwp/assets/js/datatables/dataTables.js:4105
        callback https://wordpress.xx.ie/content/plugins/mainwp/assets/js/datatables/dataTables.js:4008
        jQuery 4

**To Reproduce**

1. Update to 5.1
2. Click sites
3. Site gets stuck on "Loading..."

**Comment by bogdan-mainwp** [comment] 2024-06-19 11:08
Hi @joeczucha, thanks for reaching out. 
We are not able to duplicate this problem on our test setups.
I am assuming that this could be some plugin conflict, but I see that you have opened a support ticket with us, so someone from the support department will get back to you in short and help troubleshoot this problem.

Thanks

**Comment by joeczucha** [comment] 2024-06-19 14:54
Thanks, I've deactivated all other plugins (other than MainWP dashboard) and I'm using the TwentyTwentyFour theme. 

Let me know where I should send my Site Health report.

**Comment by bogdan-mainwp** [comment] 2024-06-20 16:32
Hi @joeczucha, might be best to do it in the private helpdesk ticket that you have started with us. Our support team is waiting for your response.

**Comment by bogdan-mainwp** [comment] 2024-09-16 15:13
@joeczucha I just noticed that this case is still open here, and after checking your helpdesk system, I found that you still did not answer our support agent. I will assume that the problem is resolved with one of the updates in the meantime. 

In case you still experience the problem, feel free to reopen your helpdesk ticket.

**Closed by bogdan-mainwp** 2024-09-16 15:13 UTC
