### ISSUE TITLE
Incomplete adding site if there are too many files on client

### ISSUE THREAD

**Issue by milsorm** [mainwp/mainwp#54] opened 2017-01-01 17:48 UTC
I use plugin "Merge + Minify + Refresh" which (unfortunately) incorrectly store a lot of cache files below `wp-content/mmr` directory. He is able to create 50+ GB a year with hundred of thousands of files. My bad, I know.

But if I try to add such site do MainWP Dashboard, it performs `getSiteStats()` which tries to collect all directories, files and their sizes. And that is unable to do in one minute so 504 Gateway timeout (nginx + php-fpm) returns back to Dashboard.

What is incomplete and incorrect? MainWP Child has all keys and options stored so he thinks that he is correctly added. Main WP Dashboard stop in "Adding site" state in JavaScript and don't finish dialog. I have to manually deactivate and reactivate Child and reload page on Dashboard and fill all data again.

Helps to prevent collecting directories and sizes in child.

My recommendation:

* solve incomplete state (don't perform first scan of directories and sizes in add site phase)
* collect dirs and sizes information at the background (can take several minutes on such sites) or tell "too many dirs" or "du -s is running too long" back to Dashboard

Admin can react on such situation (ignore it and don't have such data or remove cache files etc.).

Allow to ignore such directories like mmr cache.

I will file an issue for MMR plugin too.

Thanks
Milan

**Comment by bogdan-mainwp** [comment] 2017-01-11 13:25
Hi Milan,

Would you be able to open a support ticket at https://mainwp.com/support/?

The dev team made an update and they would like to send the update for testing if you would be able to do that. 

Thanks

**Comment by milsorm** [comment] 2017-01-11 13:26
yes, but during the weekend due to a huge amount of work in front of me... can be?

**Comment by bogdan-mainwp** [comment] 2017-01-11 13:26
Ok, that is ok. 

Thanks

**Comment by milsorm** [comment] 2017-01-22 16:46
It is the same behaviour also in new version. And of course the thing in Reconnect. So I add that call to every curl call inside utility class and after that MainWP works normally.

**Comment by milsorm** [comment] 2017-01-22 16:50
Resubmit to MainWP ticket.

**Comment by bogdan-mainwp** [comment] 2017-07-17 13:21
The dev team determined that the issue has been caused by a 3rd party plugin.

milsorm, please respond to the help desk ticket for the further troubleshooting. For now, I will go ahead and close this issue.

**Closed by bogdan-mainwp** 2017-07-17 13:21 UTC
